### ISSUE TITLE
Documentation of transfer kitten is confusing and incorrect

### ISSUE THREAD

**Issue by frabjous** [kovidgoyal/kovidgoyal.github.io#4]
There seem to be a couple problems with [the “Transfer files”](https://sw.kovidgoyal.net/kitty/kittens/transfer/) page of the kitty website for the transfer kitten.

First, the terminology is just confusing. If you're sitting in front of one computer and using it to SSH into another, and you want to transfer a file, it's weird to call the one you're SSHed into the "local" computer and the one you're sitting in front of the "remote" computer. The site defines what they mean, and yes, it's the one you're SSHed into that is running the kitten, but it's still confusing. The "send" and "receive" terminology similarly feels backwards to me. 

But worse, the documentation says that the Default direction is "send" but from what I can tell, in fact, the default direction is "receive". (At least on kitty 0.24.4.)

**Comment by kovidgoyal** [comment]
The place to report issues with kitty including its docs is
https://github.com/kovidgoyal/kitty/issues
