### ISSUE TITLE
Add Github repo link to the homepage of kitty

### ISSUE THREAD

**Issue by mmahmoudian** [kovidgoyal/kovidgoyal.github.io#5]
I would like to suggest adding a button to the sidebar of https://sw.kovidgoyal.net/kitty/ which points to https://github.com/kovidgoyal/kitty

for finding the repo i had to search for "github" on the website, go to https://sw.kovidgoyal.net/kitty/kittens/broadcast/?highlight=github and land on [a subpage of the main repo](https://github.com/kovidgoyal/kitty/tree/master/kittens/broadcast) and then go to the main page of the repo.

**Comment by kovidgoyal** [comment]
Why? The side bar is crowded enough already, why waste more space with a
link to something that is easily discovered anyway.

**Comment by mmahmoudian** [comment]
How about in the footer? The address is not as discoverable as you think. In my search engine the repo was not in the first page, but your website was the first one

**Comment by kovidgoyal** [comment]
What search engine is this? Google and Bing both show the github repo in
the first page.

**Comment by kovidgoyal** [comment]
In any case I have added a github icon to the docs footer. https://github.com/kovidgoyal/kitty/commit/1ead20a5b97fc58abf35de0e52b7f8b6bf13738d

**Comment by mmahmoudian** [comment]
> What search engine is this? Google and Bing both show the github repo in the first page.

It is Qwant. I just checked again and the main repo "is in the first page", but it is 5th and right after the sourceforge mirror. That's when I stopped looking as I thought anything lower than that should be useless items. For the sake of reproducibility:

https://www.qwant.com/?theme=1&s=0&hc=1&vt=0&b=0&l=en&locale=fi_FI&q=kitty+terminal&t=web
